#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"


cp kitty.conf ~/.config/kitty/kitty.conf
cp current-theme.conf ~/.config/kitty/current-theme.conf
"$SCRIPT_DIR/install-terminfo"
