#!/bin/bash

git config --global user.name "Oleg Morozenkov"
git config --global user.email "reo7sp@users.noreply.github.com"

git config --global url.ssh://git@github.com/.insteadOf https://github.com/
git config --global url.ssh://git@bitbucket.org/.insteadOf https://bitbucket.org/

