#!/bin/bash
set -e -o pipefail


mkdir -p ~/Library/Application\ Support/lazygit
cp lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
cp lazygit/shell.sh ~/Library/Application\ Support/lazygit/shell.sh
