#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"


mkdir -p ~/Library/Application\ Support/lazygit
cp lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
cp lazygit/shell.sh ~/Library/Application\ Support/lazygit/shell.sh
