#!/bin/bash
set -e -o pipefail

key=$1
if [[ $key == "-q" ]]; then
  QUICK_INSTALL=1
else
  QUICK_INSTALL=0
fi

confirm() {
  local message=$1

  if [[ $QUICK_INSTALL == 1 ]]; then
    false
  else
    echo -n -e "${BWhite}$message${Color_Off} [y/N] "
    read response
    case $response in
      [yY][eE][sS]|[yY])
        true
        ;;
      *)
        false
        ;;
    esac
  fi
}


git config --global user.name "Oleg Morozenkov"
git config --global user.email "m@oleg.rocks"
git config --global init.defaultBranch master

if confirm "Do you want to always use ssh instead of https to connect to github?"; then
  git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  git config --global --add url.ssh://git@github.com/.insteadOf https://reo7sp@github.com/
fi

if confirm "Use delta?"; then
  git config --global core.pager delta
  git config --global interactive.diffFilter 'delta --color-only'
  git config --global delta.navigate true
  git config --global merge.conflictStyle zdiff3
fi

if confirm "Use difftastic?"; then
  git config --global diff.external difft
  git config --global diff.tool difftastic
  git config --global difftool.difftastic.cmd 'difft "$MERGED" "$LOCAL" "abcdef1" "100644" "$REMOTE" "abcdef2" "100644"'
  git config --global difftool.prompt false
  git config --global pager.difftool true
fi

if confirm "Use sublime merge?"; then
  git config --global merge.tool smerge
fi

cp gitignore_global ~/.gitignore_global
