#!/bin/bash
set -e -o pipefail

do_install() {
  echo "$1:"
  cd "$1"
  shift
  ./install "$@"
  cd ..
  echo
}


modules=
args=
if [[ ! -z $1 ]]; then
  if [[ $1 == "-q" ]]; then
    args=$1
    shift
  fi
  modules=$@
fi

if [[ $modules == "" ]]; then
  echo "Please specify modules. Available: zsh vim kitty ranger git rg"
  echo "USAGE: ./install [-q] MODULES"
fi

for it in $modules; do
  do_install $it $args
done
