#!/bin/bash
set -e

do_install() {
  echo "$1:"
  cd "$1"
  shift
  ./install "$@"
  cd ..
  echo
}

modules="git vim zsh"
args=
if [[ ! -z $1 ]]; then
  if [[ $1 == "-q" ]]; then
    args=$1
    shift
  fi
  modules=$@
fi

for it in $modules; do
  do_install $it $args
done
