#!/bin/bash
set -e -o pipefail

do_upgrade() {
  echo "$1:"
  cd "$1"
  shift
  ./upgrade "$@"
  cd ..
  echo
}


modules=
args=
if [[ ! -z $1 ]]; then
  if [[ $1 == "-q" ]]; then
    args=$1
    shift
  fi
  modules=$@
fi

if [[ $modules == "" ]]; then
  echo "Please specify modules. Available: zsh vim"
  echo "USAGE: ./upgrade MODULES"
fi

for it in $modules; do
  do_upgrade $it $args
done
