#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"

do_upgrade() {
  echo "$1:"
  "$1/upgrade" "${@:2}"
  echo
}


modules=
args=
if [[ ! -z $1 ]]; then
  if [[ $1 == "-q" ]]; then
    args=$1
    shift
  fi
  modules=$@
fi

if [[ $modules == "" ]]; then
  echo "Please specify modules. See README.md."
  echo "USAGE: ./upgrade MODULES"
fi

for it in $modules; do
  do_upgrade $it $args
done
