os:
  shellFunctionsFile: ~/Library/Application\ Support/lazygit/shell.sh
git:
  diffRenderers:
    - colorArg: always
      command: delta --light --paging=never
gui:
  commandLogSize: 3
  border: single
