#!/bin/bash
set -e -o pipefail

key=$1
if [[ $key == "-q" ]]; then
  QUICK_INSTALL=1
else
  QUICK_INSTALL=0
fi

can-exec() {
  which "$1" 2>/dev/null 1>/dev/null
}

confirm() {
  local message=$1

  if [[ $QUICK_INSTALL == 1 ]]; then
    false
  else
    echo -n -e "${BWhite}$message${Color_Off} [y/N] "
    read response
    case $response in
      [yY][eE][sS]|[yY])
        true
        ;;
      *)
        false
        ;;
    esac
  fi
}


mkdir -p ~/.vim/{bundle,nbundle,backup,tmp,undo,sessions,spell,view} ~/.config/nvim ~/.config/nvim/{lua,after/syntax,after/ftplugin}
cp vimrc ~/.vimrc
cp nvim/init.vim ~/.config/nvim/init.vim
cp nvim/after/syntax/vim.vim ~/.config/nvim/after/syntax/vim.vim
cp nvim/after/ftplugin/jinja.vim ~/.config/nvim/after/ftplugin/jinja.vim
cp ideavimrc ~/.ideavimrc
cp neovintageousrc ~/.neovintageousrc

if [ -f ~/.config/nvim/lua/llm_corp_config.lua ]; then
  if confirm "Do you want to overwrite llm_corp_config.lua?"; then
    cp nvim/lua/llm_corp_config.lua ~/.config/nvim/lua/llm_corp_config.lua
  fi
else
  cp nvim/lua/llm_corp_config.lua ~/.config/nvim/lua/llm_corp_config.lua
fi

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -e -c "PlugInstall" -c "qa"
if can-exec nvim; then
  nvim -e -c "PlugInstall" -c "qa"
fi
