#!/bin/bash
set -e -o pipefail

can-exec() {
  which "$1" 2>/dev/null 1>/dev/null
}


if can-exec nvim; then
  nvim --headless "+Lazy! sync" +qa
  cp ~/.config/nvim/lazy-lock.json nvim/lazy-lock.json
  nvim --headless -c 'autocmd User MasonUpdateAllComplete quitall' -c 'MasonUpdateAll'
fi
