#!/bin/bash
set -e -o pipefail

can-exec() {
  which "$1" 2>/dev/null 1>/dev/null
}


vim -e -c 'PlugUpdate' -c 'qa'
if can-exec nvim; then
  nvim -e -c 'PlugUpdate' -c 'qa'
  nvim --headless -c 'autocmd User MasonUpdateAllComplete quitall' -c 'MasonUpdateAll'
fi
