#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"


nvim --headless "+Lazy! sync" +qa
cp ~/.config/nvim/lazy-lock.json nvim/lazy-lock.json
