#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"


if ! poetry run jinja2 --version >/dev/null 2>&1; then
  poetry install --no-root
fi
poetry run jinja2 -D home="$HOME" ripgreprc.j2 -o ~/.ripgreprc
poetry run jinja2 -I .. rgignore.j2 -o ~/.rgignore
