set -s escape-time 10
set -g mouse on
set -s focus-events on
set -g default-terminal tmux-256color
set -as terminal-features ',xterm-kitty:RGB,xterm-256color:RGB'
set -g set-clipboard external
set -g history-limit 100000
set -g base-index 1
set -g renumber-windows on
set -g set-titles on
set -g set-titles-string '#{=40:pane_title} [#{session_name}:#{window_index}]'
set -g status-position top
set -g status-justify left
set -g status-style 'fg=#4D4F68 bg=#E6E9EF'
set -g status-left ''
set -g status-left-length 10
set -g status-right-style 'fg=#4D4F68 bg=#E6E9EF'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g message-style 'fg=#4D4F68 bg=#BDC0CC bold'
set -g pane-border-style 'fg=#E6E9EF'
set -g pane-active-border-style 'fg=#C8C8C8'
setw -g clock-mode-colour yellow
setw -g mode-style 'fg=#EFF1F5 bg=#BDC0CC bold'
setw -g pane-base-index 1
setw -g automatic-rename on
setw -g mode-keys vi
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
setw -g window-status-current-style 'fg=#4D4F68 bg=#BDC0CC'
setw -g window-status-current-format ' #I #{pane_title} #F '
setw -g window-status-style 'fg=#A0A3B2 bg=#E6E9EF'
setw -g window-status-format ' #I #{pane_title} #F '
setw -g window-status-bell-style 'fg=#4D4F68 bg=#BDC0CC bold'
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history
bind r source-file ~/.tmux.conf
