#!/bin/sh
set -e
DOWNLOAD_URL="https://github.com/getantibody/antibody/releases/download"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"

last_version() {
  curl -s https://raw.githubusercontent.com/getantibody/homebrew-tap/master/Formula/antibody.rb |
    grep url |
    cut -f8 -d'/'
}

download() {
  version="$(last_version)" || true
  test -z "$version" && {
    echo "Unable to get antibody version."
    exit 1
  }
  echo "Downloading antibody $version for $(uname -s)_$(uname -m)..."
  rm -f "$TMPDIR/antibody.tar.gz"
  curl -s -L -o "$TMPDIR/antibody.tar.gz" \
    "$DOWNLOAD_URL/$version/antibody_$(uname -s)_$(uname -m).tar.gz"
}

extract() {
  mkdir -p "$TMPDIR/extracted"
  tar -xf "$TMPDIR/antibody.tar.gz" -C "$TMPDIR/extracted"
}

download
extract || true
mkdir -p $HOME/.antibody
mv -f "$TMPDIR/extracted/antibody" $HOME/.antibody/antibody
