#!/bin/bash
set -e -o pipefail

key=$1
if [[ $key == "-q" ]]; then
  QUICK_INSTALL=1
else
  QUICK_INSTALL=0
fi

confirm() {
  local message=$1

  if [[ $QUICK_INSTALL == 1 ]]; then
    false
  else
    echo -n -e "${BWhite}$message${Color_Off} [y/N] "
    read response
    case $response in
      [yY][eE][sS]|[yY])
        true
        ;;
      *)
        false
        ;;
    esac
  fi
}


if [ ! -d ~/.antidote ]; then
  git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
fi

if [ -f ~/.zshrc ]; then
  if confirm "Do you want to overwrite ~/.zshrc?"; then
    cp zshrc ~/.zshrc
  fi
else
  cp zshrc ~/.zshrc
fi
cp my.zshrc ~/.my.zshrc
cp zsh_plugins.txt ~/.zsh_plugins.txt
cp p10k.zsh ~/.p10k.zsh
mkdir -p ~/.config/fsh
cp overlay.ini ~/.config/fsh/overlay.ini
zsh -c 'source ~/.antidote/antidote.zsh && eval "$(antidote bundle zdharma-continuum/fast-syntax-highlighting)" && fast-theme -r && fast-theme base16 && fast-theme XDG:overlay'
mkdir -p ~/bin
cp bin/strip-whitespace ~/bin/strip-whitespace
