#!/bin/bash
set -e -o pipefail

key=$1
if [[ $key == "-q" ]]; then
  QUICK_INSTALL=1
else
  QUICK_INSTALL=0
fi

confirm() {
  local message=$1

  if [[ $QUICK_INSTALL == 1 ]]; then
    false
  else
    echo -n -e "${BWhite}$message${Color_Off} [y/N] "
    read response
    case $response in
      [yY][eE][sS]|[yY])
        true
        ;;
      *)
        false
        ;;
    esac
  fi
}

can-exec() {
  which "$1" 2>/dev/null 1>/dev/null
}


can-exec antibody || ./install-antibody
if [ -f ~/.zshrc ]; then
  if confirm "Do you want to overwrite ~/.zshrc?"; then
    cp zshrc ~/.zshrc
  fi
else
  cp zshrc ~/.zshrc
fi
cp my.zshrc ~/.my.zshrc
