#!/bin/bash
set -e -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "$SCRIPT_DIR"


mkdir -p ~/.config/ranger ~/.config/ranger/plugins
cp rc.conf ~/.config/ranger/rc.conf

if [ ! -d "$HOME/.config/ranger/plugins/zoxide" ]; then
  git clone git@github.com:jchook/ranger-zoxide.git "$HOME/.config/ranger/plugins/zoxide"
fi
if [ ! -d "$HOME/.config/ranger/plugins/ranger_fzf_filter" ]; then
  git clone git@github.com:MuXiu1997/ranger-fzf-filter.git "$HOME/.config/ranger/plugins/ranger_fzf_filter"
fi
